name: Check for updates
on:
  schedule:
    - cron: "26 5 * * *"
permissions:
  contents: write
    
jobs:
  unicode_categories:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install curl python3 python3-pip make
          pip3 install -r requirements.txt
          pip3 install bumpver
      - name: Update unicode categories and push
        run: |-
          make
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if [ "$(git diff --name-only HEAD)" ]; then
            git add -A
            timestamp=$(date -u)
            git commit -m "Updated unicode categories: ${timestamp}" || exit 0
            bumpver update --patch --push
          fi;
